- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/publish_configs.yml
- .github/workflows/release.yml
- .github/workflows/update-information.yml
> feat: add workflows

- .github/hypertrons.json
> feat: add hypertrons.json

- .github/hypertrons.json
- .github/pull_request_template.md
> feat: add pr template.md

- .github/hypertrons.json
- .github/pull_request_template.md
- .github/release.yml
> feat: add release.yml

- .github/hypertrons.json
- .github/pull_request_template.md
- .github/release.yml
- .husky/pre-commit
> feat: add husky folder

- src/pages/Background/index.ts
- src/pages/ContentScripts/index.scss
- src/pages/ContentScripts/index.ts
> feat: add pages

- src/pages/ContentScripts/components/NativePopover.tsx
- src/pages/ContentScripts/features/repo-star-tooltip/StarChart.tsx
- src/pages/ContentScripts/features/repo-star-tooltip/index.tsx
- src/pages/ContentScripts/features/repo-star-tooltip/view.tsx
> feat: add repo star tooltip feature

- src/pages/ContentScripts/features/repo-issue-tooltip/IssueChart.tsx
- src/pages/ContentScripts/features/repo-issue-tooltip/index.tsx
- src/pages/ContentScripts/features/repo-issue-tooltip/view.tsx
- src/pages/ContentScripts/features/repo-pr-tooltip/MergedLinesChart.tsx
- src/pages/ContentScripts/features/repo-pr-tooltip/PRChart.tsx
- src/pages/ContentScripts/features/repo-pr-tooltip/index.tsx
- src/pages/ContentScripts/features/repo-pr-tooltip/view.tsx
> feat: add star and issue

- src/pages/ContentScripts/features/perceptor-layout/index.tsx
- src/pages/ContentScripts/features/perceptor-layout/view.tsx
> feat: add perceptor layout feature

- src/pages/ContentScripts/features/repo-activity-openrank-trends/index.tsx
- src/pages/ContentScripts/features/repo-activity-openrank-trends/view.tsx
> feat: add repo activity openrank trends feature

- src/pages/ContentScripts/features/repo-activity-racing-bar/AvatarColorStore.ts
- src/pages/ContentScripts/features/repo-activity-racing-bar/PlayerButton.tsx
- src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx
- src/pages/ContentScripts/features/repo-activity-racing-bar/SpeedController.tsx
- src/pages/ContentScripts/features/repo-activity-racing-bar/data.ts
- src/pages/ContentScripts/features/repo-activity-racing-bar/index.tsx
- src/pages/ContentScripts/features/repo-activity-racing-bar/useLoadedAvatars.ts
- src/pages/ContentScripts/features/repo-activity-racing-bar/view.tsx
> feat: add repo activity racing bar

- src/pages/ContentScripts/features/repo-fork-tooltip/ForkChart.tsx
- src/pages/ContentScripts/features/repo-fork-tooltip/index.tsx
- src/pages/ContentScripts/features/repo-fork-tooltip/view.tsx
> feat: add repo fork tooltip

- src/pages/ContentScripts/features/repo-header-labels/ActivityChart.tsx
- src/pages/ContentScripts/features/repo-header-labels/ContributorChart.tsx
- src/pages/ContentScripts/features/repo-header-labels/OpenRankChart.tsx
- src/pages/ContentScripts/features/repo-header-labels/ParticipantChart.tsx
- src/pages/ContentScripts/features/repo-header-labels/activityView.tsx
- src/pages/ContentScripts/features/repo-header-labels/index.tsx
- src/pages/ContentScripts/features/repo-header-labels/openrankView.tsx
- src/pages/ContentScripts/features/repo-header-labels/participantView.tsx
- src/pages/ContentScripts/features/repo-header-labels/view.tsx
> feat: add repo header labels

- src/pages/ContentScripts/features/repo-networks/DataNotFound.tsx
- src/pages/ContentScripts/features/repo-networks/index.tsx
- src/pages/ContentScripts/features/repo-networks/view.tsx
> feat: add repo network graphs

- src/pages/ContentScripts/features/developer-hovercard-info/index.tsx
- src/pages/ContentScripts/features/developer-hovercard-info/view.tsx
> feat: developer hovercard info

- src/pages/ContentScripts/features/fast-pr/baseContent.ts
- src/pages/ContentScripts/features/fast-pr/giteeService.ts
- src/pages/ContentScripts/features/fast-pr/giteeUrl.ts
- src/pages/ContentScripts/features/fast-pr/githubService.ts
- src/pages/ContentScripts/features/fast-pr/handleMessage.tsx
- src/pages/ContentScripts/features/fast-pr/index.tsx
- src/pages/ContentScripts/features/fast-pr/view.tsx
> feat:add fast-pr feature

- src/pages/ContentScripts/features/repo-sidebar-labels/OpenDiggerLabel.tsx
- src/pages/ContentScripts/features/repo-sidebar-labels/index.tsx
> feat: add repo sidebar labels

- src/pages/ContentScripts/Options/Options.tsx
- src/pages/ContentScripts/Options/components/GitHubToken.tsx
- src/pages/ContentScripts/Options/components/GiteeToken.tsx
- src/pages/ContentScripts/Options/index.css
- src/pages/ContentScripts/Options/index.html
- src/pages/ContentScripts/Options/index.jsx
- src/pages/ContentScripts/Sandbox/index.html
- src/pages/ContentScripts/Sandbox/index.jsx
> feat: add options

- src/pages/ContentScripts/Popup/Popup.tsx
- src/pages/ContentScripts/Popup/index.html
- src/pages/ContentScripts/Popup/index.jsx
- keyword #xxx
- [ x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
> feat:add popup component

- src/pages/ContentScripts/features/oss-gpt/projectAnalysis.ts
> fix: fix llm

- src/pages/ContentScripts/features/oss-gpt/projectAnalysis.ts
> refactor: refactor prompt
